spring:
  profiles:
    active: local
  kafka:
    producer:
      bootstrap-servers: confluent-kafka-cluster1-cp-kafka:9092
      broker-list: confluent-kafka-cluster1-cp-kafka:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer